apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  ports:
    - port: {{ .Values.doctor.port }}
      targetPort: {{ .Values.doctor.port }}
  type: ClusterIP
