apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: {{ .Values.doctor.replicas }}
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: {{ .Values.doctor.image }}
          ports:
            - containerPort: {{ .Values.doctor.port }}
          env:
            - name: PORT
              value: "{{ .Values.doctor.port }}"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/doctor-db"
